# Generated by Django 5.0.4 on 2024-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(default=18),
        ),
    ]
