# Generated by Django 5.0.4 on 2024-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_rename_items_list_order_prodotti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(default=3),
        ),
    ]
