# Generated by Django 5.0.4 on 2024-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(default='user', max_length=50)),
                ('username', models.CharField(blank=True, default='base user', max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('phone', models.CharField(blank=True, default='00000', max_length=20, null=True)),
                ('posizione', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(default='user', max_length=50)),
                ('username', models.CharField(blank=True, default='base user', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='restaurant', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(default='00000000', max_length=20)),
                ('orarioApertura', models.DateField(blank=True, null=True)),
                ('orarioChiusura', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(default='user', max_length=50)),
                ('username', models.CharField(blank=True, default='base user', max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('balance', models.FloatField()),
                ('phone', models.CharField(blank=True, default='00000000', max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
