# Generated by Django 5.0.4 on 2024-04-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='phone',
        ),
    ]
