# Generated by Django 5.0.4 on 2024-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_baseuser_username_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(blank=True, default='user', max_length=100, null=True),
        ),
    ]
