# Generated by Django 5.0.4 on 2024-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_restaurant_name_rider_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='restaurant name', max_length=100),
        ),
    ]
