# Generated by Django 5.0.4 on 2024-04-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customer_user_remove_restaurant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='baseuser_ptr',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='baseuser_ptr',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='baseuser_ptr',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.baseuser'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.baseuser'),
        ),
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.baseuser'),
        ),
    ]
