# Generated by Django 5.0.4 on 2024-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customer_balance_remove_restaurant_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='orarioApertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='orarioChiusura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
