# Generated by Django 5.0.4 on 2024-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_restaurant_orarioapertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='orarioApertura',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='orarioChiusura',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
