# Generated by Django 5.0.4 on 2024-04-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customer_baseuser_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default='customer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='username',
            field=models.CharField(blank=True, default='restaurant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='username',
            field=models.CharField(blank=True, default='rider', max_length=100, null=True),
        ),
    ]
