# Generated by Django 5.0.4 on 2024-04-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_username_restaurant_username_rider_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='00000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='posizione',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='orarioApertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='orarioChiusura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rider',
            name='phone',
            field=models.CharField(blank=True, default='00000000', max_length=20, null=True),
        ),
    ]
