# Generated by Django 5.0.4 on 2024-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_rider_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='telefono',
            field=models.CharField(blank=True, default='+39 3332224888', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telefono',
            field=models.CharField(blank=True, default='+39 3332224888', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='telefono',
            field=models.CharField(blank=True, default='+39 3332224888', max_length=20, null=True),
        ),
    ]
