# Generated by Django 5.0.4 on 2024-05-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_position_restaurant_indirizzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='posizione',
        ),
        migrations.AddField(
            model_name='customer',
            name='favourite_restaurants',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='customer',
            name='favourites_items',
            field=models.JSONField(default=[]),
        ),
    ]
