# Generated by Django 5.0.4 on 2024-05-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customer_posizione_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='favourite_restaurants',
            new_name='prodotti_preferiti',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='favourites_items',
            new_name='ristoranti_preferiti',
        ),
    ]
