# Generated by Django 5.0.4 on 2024-05-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0011_rename_favourite_restaurants_customer_prodotti_preferiti_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('content_type', 'object_id')},
        ),
    ]
