# Generated by Django 5.0.4 on 2024-06-08 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_bankaccount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='orarioApertura',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 8, 13, 7, 28, 299637, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='orarioChiusura',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 8, 13, 7, 28, 299637, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
