# Generated by Django 5.0.4 on 2024-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_username_alter_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='username',
            field=models.CharField(blank=True, default='Rider', max_length=100),
        ),
    ]
