# Generated by Django 5.0.4 on 2024-04-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_item_restaurant'),
        ('users', '0006_customer_username_restaurant_username_rider_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.restaurant'),
        ),
    ]
